pub const GOOGLE_FONTS: &[&str] = &[
    "ABeeZee",
    "Abel",
    "Abril Fatface",
    "Acme",
    "Alegreya",
    "Alegreya Sans",
    "Alfa Slab One",
    "Almarai",
    "Amatic SC",
    "Amiri",
    "Antic Slab",
    "Anton",
    "Architects Daughter",
    "Archivo",
    "Archivo Black",
    "Archivo Narrow",
    "Arimo",
    "Armata",
    "Arvo",
    "Asap",
    "Asap Condensed",
    "Assistant",
    "Bangers",
    "Barlow",
    "Barlow Condensed",
    "Barlow Semi Condensed",
    "Bebas Neue",
    "BenchNine",
    "Bespoke",
    "Bitter",
    "Bree Serif",
    "Cabin",
    "Cabin Condensed",
    "Cairo",
    "Cantarell",
    "Cardo",
    "Catamaran",
    "Caveat",
    "Chakra Petch",
    "Changa",
    "Chivo",
    "Cinzel",
    "Comfortaa",
    "Concert One",
    "Cookie",
    "Cormorant Garamond",
    "Courgette",
    "Crete Round",
    "Crimson Text",
    "Cuprum",
    "Dancing Script",
    "Didact Gothic",
    "DM Sans",
    "DM Serif Display",
    "Domine",
    "Dosis",
    "EB Garamond",
    "Economica",
    "Exo",
    "Exo 2",
    "Figtree",
    "Fira Sans",
    "Fjalla One",
    "Francois One",
    "Frank Ruhl Libre",
    "Gloria Hallelujah",
    "Great Vibes",
    "Gudea",
    "Hammersmith One",
    "Handlee",
    "Heebo",
    "Hind",
    "Hind Madurai",
    "Hind Siliguri",
    "IBM Plex Mono",
    "IBM Plex Sans",
    "IBM Plex Serif",
    "Inconsolata",
    "Indie Flower",
    "Inter",
    "Istok Web",
    "Josefin Sans",
    "Jost",
    "Kalam",
    "Kanit",
    "Karla",
    "Kaushan Script",
    "Lato",
    "Libre Baskerville",
    "Libre Franklin",
    "Lilita One",
    "Lobster",
    "Lobster Two",
    "Lora",
    "Luckiest Guy",
    "M PLUS 1p",
    "M PLUS Rounded 1c",
    "Manrope",
    "Martel",
    "Maven Pro",
    "Merriweather",
    "Merriweather Sans",
    "Monda",
    "Montserrat",
    "Montserrat Alternates",
    "Mukta",
    "Mulish",
    "Nanum Gothic",
    "Nanum Myeongjo",
    "News Cycle",
    "Noticia Text",
    "Noto Color Emoji",
    "Noto Sans",
    "Noto Sans Arabic",
    "Noto Sans HK",
    "Noto Sans JP",
    "Noto Sans KR",
    "Noto Sans SC",
    "Noto Sans TC",
    "Noto Serif",
    "Noto Serif JP",
    "Nunito",
    "Nunito Sans",
    "Old Standard TT",
    "Open Sans",
    "Orbitron",
    "Oswald",
    "Outfit",
    "Overpass",
    "Oxygen",
    "Pacifico",
    "Passion One",
    "Pathway Gothic One",
    "Patrick Hand",
    "Patua One",
    "Paytone One",
    "Permanent Marker",
    "Philosopher",
    "Play",
    "Playfair Display",
    "Plus Jakarta Sans",
    "Poiret One",
    "Pontano Sans",
    "Poppins",
    "Prata",
    "Prompt",
    "PT Sans",
    "PT Sans Narrow",
    "PT Serif",
    "Public Sans",
    "Quattrocento",
    "Quattrocento Sans",
    "Questrial",
    "Quicksand",
    "Rajdhani",
    "Raleway",
    "Red Hat Display",
    "Righteous",
    "Roboto",
    "Roboto Condensed",
    "Roboto Mono",
    "Roboto Slab",
    "Rokkitt",
    "Ropa Sans",
    "Rubik",
    "Russo One",
    "Sacramento",
    "Saira Condensed",
    "Sanchez",
    "Sarabun",
    "Satisfy",
    "Secular One",
    "Shadows Into Light",
    "Signika",
    "Signika Negative",
    "Slabo 27px",
    "Source Code Pro",
    "Source Sans 3",
    "Space Grotesk",
    "Special Elite",
    "Tajawal",
    "Tangerine",
    "Teko",
    "Tinos",
    "Titillium Web",
    "Ubuntu",
    "Ubuntu Condensed",
    "Varela Round",
    "Volkhov",
    "Vollkorn",
    "Work Sans",
    "Yanone Kaffeesatz",
    "Yantramanav",
    "Yellowtail",
    "Zilla Slab",
];


pub const FONTS_EXTENSIONS: &[&str] = &["woff", "woff2", "ttf", "otf", "eot"];