import { ShadowsPreset } from "../domain/DesignSystemDomain";

export const PRESET_SHADOWS: ShadowsPreset[] = [
  {
    shadowName: "0",
    shadowsArray: [
      {
        color: "#959da5",
        shadowX: 0,
        shadowY: 8,
        blur: 24,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
    ],
  },
  {
    shadowName: "1",
    shadowsArray: [
      {
        color: "#64646f",
        shadowX: 0,
        shadowY: 7,
        blur: 29,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
    ],
  },
  {
    shadowName: "2",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 1.95,
        shadowY: 1.95,
        blur: 2.6,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
  },
  {
    shadowName: "3",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 5,
        blur: 15,
        spread: 0,
        colorOpacity: 0.35,
        inset: false,
      },
    ],
  },
  {
    shadowName: "4",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 4,
        spread: 0,
        colorOpacity: 0.16,
        inset: false,
      },
    ],
    author: "3drops",
  },
  {
    shadowName: "5",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 3,
        blur: 8,
        spread: 0,
        colorOpacity: 0.24,
        inset: false,
      },
    ],
  },
  {
    shadowName: "6",
    shadowsArray: [
      {
        color: "#636363",
        shadowX: 0,
        shadowY: 2,
        blur: 8,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
    ],
  },
  {
    shadowName: "7",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 4,
        spread: 0,
        colorOpacity: 0.16,
        inset: false,
      },
      {
        color: "#333",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 3,
        colorOpacity: 1,
        inset: false,
      },
    ],
  },
  {
    shadowName: "8",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 3,
        spread: 0,
        colorOpacity: 0.02,
        inset: false,
      },
      {
        color: "#1b1f23",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
  },
  {
    shadowName: "9",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 12,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "Sketch",
  },
  {
    shadowName: "10",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 54,
        blur: 55,
        spread: 0,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: -12,
        blur: 30,
        spread: 0,
        colorOpacity: 0.12,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 6,
        spread: 0,
        colorOpacity: 0.12,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 12,
        blur: 13,
        spread: 0,
        colorOpacity: 0.17,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: -3,
        blur: 5,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
    ],
  },
  {
    shadowName: "11",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 6,
        blur: 24,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.08,
        inset: false,
      },
    ],
    author: "Sketch",
  },
  {
    shadowName: "12",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 10,
        blur: 36,
        spread: 0,
        colorOpacity: 0.16,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.06,
        inset: false,
      },
    ],
    author: "Sketch",
  },
  {
    shadowName: "13",
    shadowsArray: [
      {
        color: "#110c2e",
        shadowX: 0,
        shadowY: 48,
        blur: 100,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
  },
  {
    shadowName: "14",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 50,
        blur: 100,
        spread: -20,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 30,
        blur: 60,
        spread: -30,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#0a2540",
        shadowX: 0,
        shadowY: -2,
        blur: 6,
        spread: 0,
        colorOpacity: 0.35,
        inset: true,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "15",
    shadowsArray: [
      {
        color: "#fff",
        shadowX: 0,
        shadowY: 1,
        blur: 1,
        spread: 0,
        colorOpacity: 0.1,
        inset: true,
      },
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 50,
        blur: 100,
        spread: -20,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 30,
        blur: 60,
        spread: -30,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "16",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 50,
        blur: 100,
        spread: -20,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 30,
        blur: 60,
        spread: -30,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "17",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 50,
        blur: 100,
        spread: -20,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 30,
        blur: 60,
        spread: -30,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "18",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 13,
        blur: 27,
        spread: -5,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 8,
        blur: 16,
        spread: -8,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "19",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 2,
        blur: 5,
        spread: -1,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 3,
        spread: -1,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "20",
    shadowsArray: [
      {
        color: "#26394d",
        shadowX: 0,
        shadowY: 20,
        blur: 30,
        spread: -10,
        colorOpacity: 1,
        inset: false,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "21",
    shadowsArray: [
      {
        color: "#06182c",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 2,
        colorOpacity: 0.4,
        inset: false,
      },
      {
        color: "#06182c",
        shadowX: 0,
        shadowY: 4,
        blur: 6,
        spread: -1,
        colorOpacity: 0.65,
        inset: false,
      },
      {
        color: "#fff",
        shadowX: 0,
        shadowY: 1,
        blur: 0,
        spread: 0,
        colorOpacity: 0.08,
        inset: true,
      },
    ],
    author: "Stripe",
  },
  {
    shadowName: "22",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 6,
        blur: 12,
        spread: -2,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 3,
        blur: 7,
        spread: -3,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
  },
  {
    shadowName: "23",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 13,
        blur: 27,
        spread: -5,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 8,
        blur: 16,
        spread: -8,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
  },
  {
    shadowName: "24",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 30,
        blur: 60,
        spread: -12,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 18,
        blur: 36,
        spread: -18,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
  },
  {
    shadowName: "25",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 30,
        blur: 60,
        spread: -12,
        colorOpacity: 0.25,
        inset: true,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 18,
        blur: 36,
        spread: -18,
        colorOpacity: 0.3,
        inset: true,
      },
    ],
  },
  {
    shadowName: "26",
    shadowsArray: [
      {
        color: "#32325d",
        shadowX: 0,
        shadowY: 50,
        blur: 100,
        spread: -20,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 30,
        blur: 60,
        spread: -30,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
  },
  {
    shadowName: "27",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 3,
        spread: 0,
        colorOpacity: 0.12,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 2,
        spread: 0,
        colorOpacity: 0.24,
        inset: false,
      },
    ],
    author: "Material",
  },
  {
    shadowName: "28",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 3,
        blur: 6,
        spread: 0,
        colorOpacity: 0.16,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 3,
        blur: 6,
        spread: 0,
        colorOpacity: 0.23,
        inset: false,
      },
    ],
    author: "Material",
  },
  {
    shadowName: "29",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 10,
        blur: 20,
        spread: 0,
        colorOpacity: 0.19,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 6,
        blur: 6,
        spread: 0,
        colorOpacity: 0.23,
        inset: false,
      },
    ],
    author: "Material",
  },
  {
    shadowName: "30",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 14,
        blur: 28,
        spread: 0,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 10,
        blur: 10,
        spread: 0,
        colorOpacity: 0.22,
        inset: false,
      },
    ],
    author: "Material",
  },
  {
    shadowName: "31",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 19,
        blur: 38,
        spread: 0,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 15,
        blur: 12,
        spread: 0,
        colorOpacity: 0.22,
        inset: false,
      },
    ],
    author: "Material",
  },
  {
    shadowName: "32",
    shadowsArray: [
      {
        color: "#3c4043",
        shadowX: 0,
        shadowY: 1,
        blur: 2,
        spread: 0,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#3c4043",
        shadowX: 0,
        shadowY: 2,
        blur: 6,
        spread: 2,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
    author: "Material",
  },
  {
    shadowName: "33",
    shadowsArray: [
      {
        color: "#3c4043",
        shadowX: 0,
        shadowY: 1,
        blur: 2,
        spread: 0,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#3c4043",
        shadowX: 0,
        shadowY: 1,
        blur: 3,
        spread: 1,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
    author: "Material",
  },
  {
    shadowName: "34",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "35",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 2,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "36",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 3,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 2,
        spread: 0,
        colorOpacity: 0.06,
        inset: false,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "37",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 6,
        spread: -1,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 4,
        spread: -1,
        colorOpacity: 0.06,
        inset: false,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "38",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 10,
        blur: 15,
        spread: -3,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 6,
        spread: -2,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "39",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 20,
        blur: 25,
        spread: -5,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 10,
        blur: 10,
        spread: -5,
        colorOpacity: 0.04,
        inset: false,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "40",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 25,
        blur: 50,
        spread: -12,
        colorOpacity: 0.25,
        inset: false,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "41",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 4,
        spread: 0,
        colorOpacity: 0.06,
        inset: true,
      },
    ],
    author: "Tailwind CSS",
  },
  {
    shadowName: "42",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0,
        blur: 5,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0,
        blur: 1,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
  },
  {
    shadowName: "43",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 2,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 4,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 8,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 8,
        blur: 16,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 16,
        blur: 32,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 32,
        blur: 64,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
    ],
    author: "Tobias Ahlin",
  },
  {
    shadowName: "44",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 1,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 2,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 8,
        blur: 4,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 16,
        blur: 8,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 32,
        blur: 16,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
    ],
    author: "Tobias Ahlin",
  },
  {
    shadowName: "45",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 18,
        blur: 50,
        spread: -10,
        colorOpacity: 0.2,
        inset: false,
      },
    ],
    author: "feedback.fish",
  },
  {
    shadowName: "46",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 10,
        blur: 50,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
  },
  {
    shadowName: "47",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 3,
        blur: 5,
        spread: 0,
        colorOpacity: 0.04,
        inset: false,
      },
    ],
  },
  {
    shadowName: "48",
    shadowsArray: [
      {
        color: "#f02eaa",
        shadowX: -5,
        shadowY: 5,
        blur: 0,
        spread: 0,
        colorOpacity: 0.4,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: -10,
        shadowY: 10,
        blur: 0,
        spread: 0,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: -15,
        shadowY: 15,
        blur: 0,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: -20,
        shadowY: 20,
        blur: 0,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: -25,
        shadowY: 25,
        blur: 0,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "Alligator",
  },
  {
    shadowName: "49",
    shadowsArray: [
      {
        color: "#f02eaa",
        shadowX: 0,
        shadowY: 5,
        blur: 0,
        spread: 0,
        colorOpacity: 0.4,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 0,
        shadowY: 10,
        blur: 0,
        spread: 0,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 0,
        shadowY: 15,
        blur: 0,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 0,
        shadowY: 20,
        blur: 0,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 0,
        shadowY: 25,
        blur: 0,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "Alligator",
  },
  {
    shadowName: "50",
    shadowsArray: [
      {
        color: "#f02eaa",
        shadowX: 5,
        shadowY: 5,
        blur: 0,
        spread: 0,
        colorOpacity: 0.4,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 10,
        shadowY: 10,
        blur: 0,
        spread: 0,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 15,
        shadowY: 15,
        blur: 0,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 20,
        shadowY: 20,
        blur: 0,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#f02eaa",
        shadowX: 25,
        shadowY: 25,
        blur: 0,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "Alligator",
  },
  {
    shadowName: "51",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 1,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 2,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 4,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 8,
        blur: 8,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 16,
        blur: 16,
        spread: 0,
        colorOpacity: 0.07,
        inset: false,
      },
    ],
  },
  {
    shadowName: "52",
    shadowsArray: [
      {
        color: "#434755",
        shadowX: 0,
        shadowY: 0,
        blur: 0.25,
        spread: 0,
        colorOpacity: 0.27,
        inset: false,
      },
      {
        color: "#5a7dbc",
        shadowX: 0,
        shadowY: 0.25,
        blur: 1,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "pqina.nl/doka",
  },
  {
    shadowName: "53",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 2,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
  },
  {
    shadowName: "54",
    shadowsArray: [
      {
        color: "#1b1f23",
        shadowX: 0,
        shadowY: 1,
        blur: 0,
        spread: 0,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#fff",
        shadowX: 0,
        shadowY: 1,
        blur: 0,
        spread: 0,
        colorOpacity: 0.25,
        inset: true,
      },
    ],
    author: "Github",
  },
  {
    shadowName: "55",
    shadowsArray: [
      {
        color: "#0366d6",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 3,
        colorOpacity: 0.3,
        inset: false,
      },
    ],
    author: "Github",
  },
  {
    shadowName: "56",
    shadowsArray: [
      {
        color: "#0e1e25",
        shadowX: 0,
        shadowY: 2,
        blur: 4,
        spread: 0,
        colorOpacity: 0.12,
        inset: false,
      },
      {
        color: "#0e1e25",
        shadowX: 0,
        shadowY: 2,
        blur: 16,
        spread: 0,
        colorOpacity: 0.32,
        inset: false,
      },
    ],
  },
  {
    shadowName: "57",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 12,
        blur: 28,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 4,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#fff",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.05,
        inset: true,
      },
    ],
    author: "Facebook",
  },
  {
    shadowName: "58",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 5,
        blur: 15,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
    author: "Shopify",
  },
  {
    shadowName: "59",
    shadowsArray: [
      {
        color: "#212326",
        shadowX: 0,
        shadowY: 10,
        blur: 10,
        spread: -10,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "Shopify",
  },
  {
    shadowName: "60",
    shadowsArray: [
      {
        color: "#ccdbe8",
        shadowX: 3,
        shadowY: 3,
        blur: 6,
        spread: 0,
        colorOpacity: 1,
        inset: true,
      },
      {
        color: "#fff",
        shadowX: -3,
        shadowY: -3,
        blur: 6,
        spread: 1,
        colorOpacity: 0.5,
        inset: true,
      },
    ],
    author: "boxshadows.com",
  },
  {
    shadowName: "61",
    shadowsArray: [
      {
        color: "#88a5bf",
        shadowX: 6,
        shadowY: 2,
        blur: 16,
        spread: 0,
        colorOpacity: 0.48,
        inset: false,
      },
      {
        color: "#fff",
        shadowX: -6,
        shadowY: -2,
        blur: 16,
        spread: 0,
        colorOpacity: 0.8,
        inset: false,
      },
    ],
    author: "boxshadows.com",
  },
  {
    shadowName: "62",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 1,
        blur: 0,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "63",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 1,
        blur: 0,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 0,
        blur: 8,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "64",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 0,
        blur: 16,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "65",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 4,
        blur: 16,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 8,
        blur: 32,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "66",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 4,
        blur: 16,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 8,
        blur: 32,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "67",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 1,
        blur: 0,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 8,
        blur: 24,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 16,
        blur: 48,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "68",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 4,
        blur: 16,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 8,
        blur: 24,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 16,
        blur: 56,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "69",
    shadowsArray: [
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 8,
        blur: 24,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 16,
        blur: 56,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
      {
        color: "#11111a",
        shadowX: 0,
        shadowY: 24,
        blur: 80,
        spread: 0,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "box-shadows.co",
  },
  {
    shadowName: "70",
    shadowsArray: [
      {
        color: "#323269",
        shadowX: 0,
        shadowY: 2,
        blur: 5,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 1,
        blur: 1,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "10er.app",
  },
  {
    shadowName: "71",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 15,
        blur: 25,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 5,
        blur: 10,
        spread: 0,
        colorOpacity: 0.05,
        inset: false,
      },
    ],
    author: "wip.chat",
  },
  {
    shadowName: "72",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 2.4,
        shadowY: 2.4,
        blur: 3.2,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
  },
  {
    shadowName: "73",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 3,
        blur: 3,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
    author: "Airbnb",
  },
  {
    shadowName: "74",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 12,
        spread: 0,
        colorOpacity: 0.08,
        inset: false,
      },
    ],
    author: "Airbnb",
  },
  {
    shadowName: "75",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 8,
        spread: 0,
        colorOpacity: 0.15,
        inset: false,
      },
    ],
    author: "Airbnb",
  },
  {
    shadowName: "76",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 4,
        spread: 0,
        colorOpacity: 0.18,
        inset: false,
      },
    ],
    author: "Airbnb",
  },
  {
    shadowName: "77",
    shadowsArray: [
      {
        color: "#000",
        shadowX: -4,
        shadowY: 9,
        blur: 25,
        spread: -6,
        colorOpacity: 0.1,
        inset: false,
      },
    ],
    author: "ls.graphics",
  },
  {
    shadowName: "78",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 60,
        blur: 40,
        spread: -7,
        colorOpacity: 0.2,
        inset: false,
      },
    ],
    author: "ls.graphics",
  },
  {
    shadowName: "79",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 30,
        blur: 90,
        spread: 0,
        colorOpacity: 0.4,
        inset: false,
      },
    ],
    author: "Lonely Planet",
  },
  {
    shadowName: "80",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 22,
        blur: 70,
        spread: 4,
        colorOpacity: 0.56,
        inset: false,
      },
    ],
    author: "Mac",
  },
  {
    shadowName: "81",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 20,
        blur: 30,
        spread: 0,
        colorOpacity: 0.2,
        inset: false,
      },
    ],
    author: "Mac",
  },
  {
    shadowName: "82",
    shadowsArray: [
      {
        color: "#fff",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.2,
        inset: true,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.9,
        inset: false,
      },
    ],
    author: "Mac",
  },
  {
    shadowName: "83",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0.0625,
        blur: 0.0625,
        spread: 0,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0.125,
        blur: 0.5,
        spread: 0,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#fff",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.1,
        inset: true,
      },
    ],
    author: "pqina.nl/doka",
  },
  {
    shadowName: "84",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 3,
        blur: 12,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
    ],
    author: "Typedream",
  },
  {
    shadowName: "85",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: -23,
        blur: 25,
        spread: 0,
        colorOpacity: 0.17,
        inset: true,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: -36,
        blur: 30,
        spread: 0,
        colorOpacity: 0.15,
        inset: true,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: -79,
        blur: 40,
        spread: 0,
        colorOpacity: 0.1,
        inset: true,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 1,
        spread: 0,
        colorOpacity: 0.06,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 4,
        blur: 2,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 8,
        blur: 4,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 16,
        blur: 8,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 32,
        blur: 16,
        spread: 0,
        colorOpacity: 0.09,
        inset: false,
      },
    ],
  },
  {
    shadowName: "86",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 25,
        blur: 20,
        spread: -20,
        colorOpacity: 0.45,
        inset: false,
      },
    ],
  },
  {
    shadowName: "87",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 2,
        blur: 4,
        spread: 0,
        colorOpacity: 0.4,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: 7,
        blur: 13,
        spread: -3,
        colorOpacity: 0.3,
        inset: false,
      },
      {
        color: "#000",
        shadowX: 0,
        shadowY: -3,
        blur: 0,
        spread: 0,
        colorOpacity: 0.2,
        inset: true,
      },
    ],
  },
  {
    shadowName: "88",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.05,
        inset: false,
      },
      {
        color: "#d1d5db",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 1,
        inset: true,
      },
    ],
  },
  {
    shadowName: "89",
    shadowsArray: [
      {
        color: "#000",
        shadowX: 0,
        shadowY: -50,
        blur: 36,
        spread: -28,
        colorOpacity: 0.35,
        inset: true,
      },
    ],
  },
  {
    shadowName: "90",
    shadowsArray: [
      {
        color: "#091e42",
        shadowX: 0,
        shadowY: 1,
        blur: 1,
        spread: 0,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#091e42",
        shadowX: 0,
        shadowY: 0,
        blur: 1,
        spread: 1,
        colorOpacity: 0.13,
        inset: false,
      },
    ],
    author: "Trello",
  },
  {
    shadowName: "91",
    shadowsArray: [
      {
        color: "#091e42",
        shadowX: 0,
        shadowY: 4,
        blur: 8,
        spread: -2,
        colorOpacity: 0.25,
        inset: false,
      },
      {
        color: "#091e42",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.08,
        inset: false,
      },
    ],
    author: "Trello",
  },
  {
    shadowName: "92",
    shadowsArray: [
      {
        color: "#0e3f7e",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#2a3345",
        shadowX: 0,
        shadowY: 1,
        blur: 1,
        spread: -0.5,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 3,
        blur: 3,
        spread: -1.5,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 6,
        blur: 6,
        spread: -3,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#0e3f7e",
        shadowX: 0,
        shadowY: 12,
        blur: 12,
        spread: -6,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#0e3f7e",
        shadowX: 0,
        shadowY: 24,
        blur: 24,
        spread: -12,
        colorOpacity: 0.04,
        inset: false,
      },
    ],
    author: "Antimetal",
  },
  {
    shadowName: "93",
    shadowsArray: [
      {
        color: "#0e3f7e",
        shadowX: 0,
        shadowY: 0,
        blur: 0,
        spread: 1,
        colorOpacity: 0.06,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 1,
        blur: 1,
        spread: -0.5,
        colorOpacity: 0.03,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 2,
        blur: 2,
        spread: -1,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 3,
        blur: 3,
        spread: -1.5,
        colorOpacity: 0.04,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 5,
        blur: 5,
        spread: -2.5,
        colorOpacity: 0.03,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 10,
        blur: 10,
        spread: -5,
        colorOpacity: 0.03,
        inset: false,
      },
      {
        color: "#2a3346",
        shadowX: 0,
        shadowY: 24,
        blur: 24,
        spread: -8,
        colorOpacity: 0.03,
        inset: false,
      },
    ],
    author: "Antimetal",
  },
];
